### ISSUE TITLE
Refactor Public & Private Run API

### ISSUE THREAD

**Issue by isidentical** [thg-consulting/inspectortiger#18]

**Comment by Rexogamer** [comment]
what file(s) in particular?

**Comment by isidentical** [comment]
When i was working on `inspectortiger.server` i realized the `inspects.py` is badly designed. Also `config_manager.py` is so crowded, the plugin system should be extracted to another module.

**Comment by isidentical** [comment]
I am thinking a session system which can replace both `inspects` and `config_manager` module.

**Comment by isidentical** [comment]
```
Session
> Session.load_plugins(self, *plugins: List[Plugin])
> Session.single_inspection(self, file: Path)
> Session.bulk_inspection(self, *files: List[Path])
> Session.merge_inspections(self, inspections: Iterator[Inspection])
```

After this session implementation we no longer need `inspectortiger.inspects` module and `inspectortiger.config_manager.ConfigManager` class. All config system can be handled with-in a new `config` module. Also `Plugin`, `_Plugin` will become a single `plugin` module.
